### ISSUE TITLE
Add new function, which calculate interfaceID for URIStorage standard

### ISSUE THREAD

**Issue by JackBekket** [MoonSHRD/TelegramNFTMarketplace#1]
https://github.com/MoonSHRD/TelegramNFTMarketplace/blob/aa45961f35917c88052f94e37329e0753d672140/contracts/InterfaceRegister.sol#L56

**Comment by daseinsucks** [comment]
Done

https://github.com/MoonSHRD/TelegramNFTMarketplace/blob/7ffead87dadd2b99d7b0304578df97cf3d8a3f8d/contracts/InterfaceRegister.sol#L62
