### ISSUE TITLE
Fix buyTelegram page

### ISSUE THREAD

**Issue by JackBekket** [MoonSHRD/TelegramNFTMarketplace#15]
Add `file_id` to GET query along with currency
show img as it done at sellTelegram page

**Comment by daseinsucks** [comment]
Done. Link should look like /buy_telegram?token_id=4&price=1000&currency=5&collection_contract_address=0x2b1e0A2b16AB524Ad3f4273d1ecB63FC3b9cB58C
or it'll crash
